/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * SilkwormAPI
 * API для интернет-магазина
 * OpenAPI spec version: v1
 */

export interface AddressResponseDto {
  /** @minLength 1 */
  Country: string;
  /** @minLength 1 */
  City: string;
  /** @minLength 1 */
  PostalCode: string;
  /** @minLength 1 */
  Street: string;
  /** @minLength 1 */
  House: string;
  /** @minLength 1 */
  Apartment: string;
  /** @nullable */
  AdditionalInfo?: string | null;
}
