/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * SilkwormAPI
 * API для интернет-магазина
 * OpenAPI spec version: v1
 */
import type { UserResponseDto } from './userResponseDto';

export interface AuthResponseDto {
  User: UserResponseDto;
  /** @minLength 1 */
  AccessToken: string;
  /** @minLength 1 */
  RefreshToken: string;
}
