/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * SilkwormAPI
 * API для интернет-магазина
 * OpenAPI spec version: v1
 */
import type { CategoryResponseDto } from './categoryResponseDto';

export interface CategoryTreeResponseDto {
  Id: string;
  /** @minLength 1 */
  Title: string;
  /** @minLength 1 */
  Slug: string;
  Children: CategoryResponseDto[];
}
