/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * SilkwormAPI
 * API для интернет-магазина
 * OpenAPI spec version: v1
 */

export interface CreateProductVariantDto {
  ProductId: string;
  /**
   * @minLength 1
   * @maxLength 20
   */
  Size: string;
  /**
   * @minLength 1
   * @maxLength 50
   */
  Color: string;
  /**
   * @minimum 0
   * @maximum 2147483647
   */
  StockCount: number;
}
