/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * SilkwormAPI
 * API для интернет-магазина
 * OpenAPI spec version: v1
 */
import type { CreateAddressDto } from './createAddressDto';
import type { CreateOrderItemDto } from './createOrderItemDto';

export interface CreateOrderDto {
  /** @minItems 1 */
  Items: CreateOrderItemDto[];
  DeliveryAddress: CreateAddressDto;
  /**
   * @minLength 1
   * @maxLength 20
   */
  ContactPhone: string;
}
