/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * SilkwormAPI
 * API для интернет-магазина
 * OpenAPI spec version: v1
 */

export interface CreateCategoryDto {
  /**
   * @minLength 1
   * @maxLength 100
   */
  Title: string;
  /**
   * @minLength 1
   * @maxLength 100
   * @pattern ^[a-z0-9]+(?:-[a-z0-9]+)*$
   */
  Slug: string;
  /** @nullable */
  ParentId?: string | null;
}
