/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * SilkwormAPI
 * API для интернет-магазина
 * OpenAPI spec version: v1
 */

export interface CreateAddressDto {
  /**
   * @minLength 1
   * @maxLength 100
   */
  Country: string;
  /**
   * @minLength 1
   * @maxLength 100
   */
  City: string;
  /**
   * @minLength 1
   * @maxLength 20
   */
  PostalCode: string;
  /**
   * @minLength 1
   * @maxLength 200
   */
  Street: string;
  /**
   * @minLength 1
   * @maxLength 10
   */
  House: string;
  /**
   * @minLength 1
   * @maxLength 10
   */
  Apartment: string;
  /**
   * @maxLength 500
   * @nullable
   */
  AdditionalInfo?: string | null;
}
