/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * SilkwormAPI
 * API для интернет-магазина
 * OpenAPI spec version: v1
 */

export interface CreateGalleryImageDto {
  /** @minLength 1 */
  Url: string;
  /** @nullable */
  Description?: string | null;
}
