/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * SilkwormAPI
 * API для интернет-магазина
 * OpenAPI spec version: v1
 */

export type GetApiV1ProductsParams = {
categoryId?: string;
size?: string;
color?: string;
minPrice?: number;
maxPrice?: number;
search?: string;
sort?: string;
page?: number;
pageSize?: number;
};
