/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * SilkwormAPI
 * API для интернет-магазина
 * OpenAPI spec version: v1
 */
import type { OrderStatus } from './orderStatus';
import type { PaymentStatus } from './paymentStatus';

export type GetApiV1AdminAdminOrdersParams = {
status?: OrderStatus;
paymentStatus?: PaymentStatus;
fromDate?: string;
toDate?: string;
page?: number;
pageSize?: number;
};
