/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * SilkwormAPI
 * API для интернет-магазина
 * OpenAPI spec version: v1
 */

export type GetApiV1UploadProductImagesParams = {
page?: number;
pageSize?: number;
search?: string;
};
