/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * SilkwormAPI
 * API для интернет-магазина
 * OpenAPI spec version: v1
 */

export interface ImageInfoResponseDto {
  /** @minLength 1 */
  FileName: string;
  /** @minLength 1 */
  Url: string;
  FileSize: number;
  CreatedDate: string;
  /** @minLength 1 */
  MimeType: string;
}
