/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * SilkwormAPI
 * API для интернет-магазина
 * OpenAPI spec version: v1
 */
import type { ImageInfoResponseDto } from './imageInfoResponseDto';

export interface ImagesListResponseDto {
  Images: ImageInfoResponseDto[];
  TotalCount: number;
  /** @minLength 1 */
  DirectoryPath: string;
}
