/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * SilkwormAPI
 * API для интернет-магазина
 * OpenAPI spec version: v1
 */

export interface LoginDto {
  /** @minLength 1 */
  Email: string;
  /** @minLength 1 */
  Password: string;
}
