/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * SilkwormAPI
 * API для интернет-магазина
 * OpenAPI spec version: v1
 */
import type { OrderStatus } from './orderStatus';
import type { PaymentStatus } from './paymentStatus';

export interface OrderListItemResponseDto {
  Id: string;
  TotalPrice: number;
  CreatedAt: string;
  Status: OrderStatus;
  PaymentStatus: PaymentStatus;
  ItemsCount: number;
}
