/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * SilkwormAPI
 * API для интернет-магазина
 * OpenAPI spec version: v1
 */
import type { AddressResponseDto } from './addressResponseDto';
import type { OrderItemDetailsResponseDto } from './orderItemDetailsResponseDto';
import type { OrderStatus } from './orderStatus';
import type { PaymentStatus } from './paymentStatus';

export interface OrderDetailsResponseDto {
  Id: string;
  UserId: string;
  Items: OrderItemDetailsResponseDto[];
  TotalPrice: number;
  DeliveryAddress: AddressResponseDto;
  /** @minLength 1 */
  ContactPhone: string;
  Status: OrderStatus;
  PaymentStatus: PaymentStatus;
  CreatedAt: string;
}
