/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * SilkwormAPI
 * API для интернет-магазина
 * OpenAPI spec version: v1
 */
import type { OrderAdminListItemResponseDto } from './orderAdminListItemResponseDto';

export interface OrderAdminListItemResponseDtoPaginatedResponse {
  /** @nullable */
  Items?: OrderAdminListItemResponseDto[] | null;
  Total?: number;
  Page?: number;
  PageSize?: number;
  readonly TotalPages?: number;
}
