/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * SilkwormAPI
 * API для интернет-магазина
 * OpenAPI spec version: v1
 */

export interface OrderItemDetailsResponseDto {
  Id: string;
  ProductId: string;
  /** @nullable */
  VariantId?: string | null;
  /** @minLength 1 */
  ProductTitle: string;
  /** @minLength 1 */
  ProductImage: string;
  /** @minLength 1 */
  Size: string;
  /** @minLength 1 */
  Color: string;
  Quantity: number;
  PriceAtMoment: number;
  readonly Subtotal: number;
}
