/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * SilkwormAPI
 * API для интернет-магазина
 * OpenAPI spec version: v1
 */
import type { ProductListItemResponseDto } from './productListItemResponseDto';

export interface ProductListItemResponseDtoPaginatedResponse {
  /** @nullable */
  Items?: ProductListItemResponseDto[] | null;
  Total?: number;
  Page?: number;
  PageSize?: number;
  readonly TotalPages?: number;
}
