/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * SilkwormAPI
 * API для интернет-магазина
 * OpenAPI spec version: v1
 */

export interface ProductVariantResponseDto {
  Id: string;
  /** @minLength 1 */
  Size: string;
  /** @minLength 1 */
  Color: string;
  StockCount: number;
}
