/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * SilkwormAPI
 * API для интернет-магазина
 * OpenAPI spec version: v1
 */

export interface ProductListItemResponseDto {
  Id: string;
  /** @minLength 1 */
  Title: string;
  Price: number;
  /** @nullable */
  DiscountPrice?: number | null;
  /** @minLength 1 */
  Preview: string;
  CategoryId: string;
  /** @minLength 1 */
  CategoryTitle: string;
}
