/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * SilkwormAPI
 * API для интернет-магазина
 * OpenAPI spec version: v1
 */

export interface RegisterDto {
  /**
   * @minLength 1
   * @maxLength 256
   */
  Email: string;
  /** @minLength 8 */
  Password: string;
  /**
   * @minLength 1
   * @maxLength 100
   */
  Name: string;
  /**
   * @minLength 0
   * @maxLength 11
   * @nullable
   */
  Phone?: string | null;
}
