/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * SilkwormAPI
 * API для интернет-магазина
 * OpenAPI spec version: v1
 */

export interface TokenResponseDto {
  /** @minLength 1 */
  AccessToken: string;
}
