/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * SilkwormAPI
 * API для интернет-магазина
 * OpenAPI spec version: v1
 */
import type { UpdateAddressDto } from './updateAddressDto';

export interface UpdateUserDto {
  /**
   * @maxLength 100
   * @nullable
   */
  Name?: string | null;
  /**
   * @maxLength 20
   * @nullable
   */
  Phone?: string | null;
  Address?: UpdateAddressDto;
}
