/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * SilkwormAPI
 * API для интернет-магазина
 * OpenAPI spec version: v1
 */

export interface UpdateAddressDto {
  /**
   * @maxLength 100
   * @nullable
   */
  Country?: string | null;
  /**
   * @maxLength 100
   * @nullable
   */
  City?: string | null;
  /**
   * @maxLength 20
   * @nullable
   */
  PostalCode?: string | null;
  /**
   * @maxLength 200
   * @nullable
   */
  Street?: string | null;
  /**
   * @maxLength 10
   * @nullable
   */
  House?: string | null;
  /**
   * @maxLength 10
   * @nullable
   */
  Apartment?: string | null;
  /**
   * @maxLength 500
   * @nullable
   */
  AdditionalInfo?: string | null;
}
