/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * SilkwormAPI
 * API для интернет-магазина
 * OpenAPI spec version: v1
 */

export interface UpdateProductVariantDto {
  /**
   * @maxLength 20
   * @nullable
   */
  Size?: string | null;
  /**
   * @maxLength 50
   * @nullable
   */
  Color?: string | null;
  /**
   * @minimum 0
   * @maximum 2147483647
   * @nullable
   */
  StockCount?: number | null;
}
