/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * SilkwormAPI
 * API для интернет-магазина
 * OpenAPI spec version: v1
 */
import type { PaymentStatus } from './paymentStatus';

export interface UpdateOrderPaymentStatusDto {
  PaymentStatus?: PaymentStatus;
}
