/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * SilkwormAPI
 * API для интернет-магазина
 * OpenAPI spec version: v1
 */

export interface UpdateCategoryDto {
  /**
   * @maxLength 100
   * @nullable
   */
  Title?: string | null;
  /**
   * @maxLength 100
   * @nullable
   * @pattern ^[a-z0-9]+(?:-[a-z0-9]+)*$
   */
  Slug?: string | null;
  /** @nullable */
  ParentId?: string | null;
}
