/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * SilkwormAPI
 * API для интернет-магазина
 * OpenAPI spec version: v1
 */

export interface UploadResponseDto {
  /** @minLength 1 */
  OriginalUrl: string;
  /** @minLength 1 */
  FileName: string;
  /** @minLength 1 */
  OriginalFileName: string;
  /** @nullable */
  CustomNameUsed?: string | null;
  FileSize: number;
  /** @minLength 1 */
  MimeType: string;
  UploadDate: string;
  Success: boolean;
  /** @nullable */
  Error?: string | null;
  Index: number;
}
