/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * SilkwormAPI
 * API для интернет-магазина
 * OpenAPI spec version: v1
 */
import type { AddressResponseDto } from './addressResponseDto';

export interface UserResponseDto {
  Id: string;
  /** @minLength 1 */
  Email: string;
  /** @minLength 1 */
  Name: string;
  /** @nullable */
  Phone?: string | null;
  Address?: AddressResponseDto;
}
